### ISSUE TITLE
Can not find the settings file

### ISSUE THREAD

**Issue by codingwatching** [NriotHrreion/Snake-ts#2] opened 2021-12-26 05:18 UTC
Hi @NriotHrreion 
I try to run the game but there is an error here, thank you!

Uncaught TypeError: Cannot read properties of null (reading 'generateWall')
    at new Game (Game.tsx:45)
    at constructClassInstance (react-dom.development.js:12709)
    at updateClassComponent (react-dom.development.js:17425)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at scheduleUpdateOnFiber (react-dom.development.js:21881)
    at updateContainer (react-dom.development.js:25482)
    at react-dom.development.js:26021
    at unbatchedUpdates (react-dom.development.js:22431)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020)
    at Object.render (react-dom.development.js:26103)
    at Module.<anonymous> (index.tsx:7)
    at Module../src/index.tsx (index.tsx:9)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Object.1 (utils.tsx:4)
    at __webpack_require__ (bootstrap:851)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

**Comment by NriotHrreion** [comment] 2022-01-01 00:43
Thanks for your issue!
But I can't reproduce this error. Can you explain to me how do you get this error?

I'll try my best to fix the bug.

**Comment by codingwatching** [comment] 2022-01-04 03:00
Hi @NriotHrreion 
I am following 4 steps on the readme
Now I see an error on the web like this image bellow
I think the game can not find the snake-ts.settings file
![image](https://user-images.githubusercontent.com/85933804/148003720-edab1ce7-b762-4bf3-aeda-9fa6c97b862b.png)

**Comment by codingwatching** [comment] 2022-01-04 03:01
![image](https://user-images.githubusercontent.com/85933804/148003906-9bb82b6e-fe53-4022-a2d1-a284c596734f.png)
![image](https://user-images.githubusercontent.com/85933804/148003944-a9065fbc-b61c-4412-9ddc-dec8855e8c63.png)

**Comment by NriotHrreion** [comment] 2022-01-08 12:36
The bug has been fixed in the commit https://github.com/NriotHrreion/Snake-ts/commit/bedd611e2f76ade3fd9d24c58672ad65f8645c73
Please re-do the 4 steps in readme and try again.

**Closed as completed by NriotHrreion** 2022-01-08 12:36 UTC
Labels: bug
